# Generated by Django 5.0.6 on 2024-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
    ]
