# Generated by Django 5.0.6 on 2024-09-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_min_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='approved',
        ),
    ]
